### PR TITLE
feat(bin): added run time option to config file path and name

### PR DESCRIPTION
**Pull request by valorkin**
Hey, It would be really good to have an option for custom path to configuration
especially if you hate dozen of files in your project root folder (like me)
or have to run different configuration for different needs

Thanks in advance

Regards, Dima

### CODE REVIEW

**Comment by valorkin** [comment]
@johnpapa please review

**Comment by johnpapa** [comment]
i like the idea. @cgmartin is this how you would like to do it? i prefer `yargs` myself.

**Comment by cgmartin** [comment]
This looks good to me. I like the fact that it matches names with the [browsersync `--config` option](https://www.browsersync.io/docs/command-line/).

Yargs is what I'm most comfortable with, but minimist is fine. There are [several popular args modules out there](https://npmcompare.com/compare/commander,minimist,nomnom,optimist,yargs) that all score pretty high. What we're doing here is pretty simple/straightforward in terms of arg options. Easy to replace if need be.

@johnpapa good to merge? Thanks for the PR @valorkin !

**Comment by johnpapa** [comment]
i havent had a chance to test it ... have you Chris? If so, Im cool with it as long as it ups the version number by a minor.

**Comment by cgmartin** [comment]
Tested it, works fine. Merging and bumping minor version.

**Comment by johnpapa** [comment]
Since it changes the API (not breaking), Shouldn't this be a minor bump to 2.1.0 ? (not a patch)

**Comment by johnpapa** [comment]
i bumped it to 2.1.0 and published

**Comment by cgmartin** [comment]
yes, minor, I fubar. Thanks for fix

**Comment by johnpapa** [comment]
no worries. thanks for testing

**Pull request merged**
